project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'

urlpatterns = [
    path('Home/', views.home, name="Home"),
    path('recipes/category/<category_id>/', views.category, name="category"),
    path('recipes/<recipe_id>/', views.recipe, name="recipe"),
    
]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=65)
    def __str__(self):
        return self.name

class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField()
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/covers/%Y/%m/%d/')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null = True
    )
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null = True, blank = True, default = None
    )
    def __str__(self):
        return self.title
    
# Create your models here.

recipes/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from utils.recipes.factory import make_recipe
from django.http import HttpResponse
from recipes.models import Recipe


def home(request):
    recipes = Recipe.objects.filter(is_published = True).order_by('-id')
    #recipes = get_list_or_404( Recipe.objects.filter(is_published=True,).order_by('-id'))
    return render(request,'recipes/pages/home.html', context={
        'recipes': recipes,
        'is_detail_page': False,
    })

def category(request, category_id):
    #recipes = Recipe.objects.filter(is_published=True,category__id=category_id,).order_by('-id')
    
    recipes = get_list_or_404( Recipe.objects.filter(is_published=True,category__id=category_id,).order_by('-id'))

    return render(request,'recipes/pages/category.html', context={
        'recipes': recipes,
        'title': f'{recipes[0].category.name}'
    })

def recipe(request, recipe_id):
    #recipe = Recipe.objects.filter(is_published = True, pk = recipe_id).order_by('-id').first()

    recipe = get_object_or_404(
        Recipe,
        is_published = True,
        pk = recipe_id)
    
    return render(request,'recipes/pages/recipe-view.html', context={
       'recipe': recipe,
        'is_detail_page': True,
    })
# Create your views here.

recipes/templates/recipes/pages/category.html
{% extends 'global/base.html'%}
{%block title%} {{ title }} Category | {%endblock title%}
{% block content %}
<div class="main-content main-content-list container">
    {% for recipe in recipes%} 
        {% include 'recipes/partials/recipe.html' %}
    {%endfor%}
</div>
{% endblock content %}

recipes/templates/recipes/pages/home.html
{% extends 'global/base.html' %}
{% block title %}
    List |
{% endblock title %}
{% block content %}
    <div class="main-content main-content-list container">
        {% for recipe in recipes %}
            {% include 'recipes/partials/recipe.html' %}
        {% empty %}   
            <h1 class="center">No recipes found here</h1> 
        {% endfor %}

    </div>
{% endblock content %}

recipes/templates/recipes/pages/recipe-view.html
{% extends 'global/base.html' %}
{% block title %}
        {{ recipe.title }} |
{% endblock title %}
{% block content %}
        <div class="main-content main-content-detail container">{% include 'recipes/partials/recipe.html' %}</div>
{% endblock content %}

recipes/templates/recipes/partials/footer.html
<footer class="main-footer">
    <div class="developer">
      <a href="https://www.otaviomiranda.com.br/" target="_blank" rel="noreferrer noopener">By Everton Mutti</a>
    </div>
  
    <div class="powered">
      <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
    </div>
  </footer>

recipes/templates/recipes/partials/head.html
{% load static %}

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

recipes/templates/recipes/partials/header.html
<header class="main-header">
    <div>
        <h1>
            <a href="{% url 'recipes:Home'%}">
                <i class="fas fa-utensils logo-icon" id="fa"></i>
                <span>
                    Recipes
                </span>
            </a>
        </h1>
    </div>
</header>

recipes/templates/recipes/partials/recipe.html
<div class="recipe recipe-list-item">
    <div class="recipe-cover">
        <a href="{% url 'recipes:recipe' recipe.id %}">
            <img src="{{ recipe.cover.url }}" alt="">
        </a>
    </div>
    <div class="recipe-title-container">
        <h2 class="recipe-title">
            <a href="{% url 'recipes:recipe' recipe.id %}">{{ recipe.title }}</a>
        </h2>
    </div>
    <div class="recipe-author">
        {% if recipe.author != None %}
            <span class="recipe-author-item">
                <i class="fas fa-user"></i>
                {% if recipe.author.first_name %}
                    {{ recipe.author.first_name }} {{ recipe.author.last_name }}
                {% else %}
                    {{ recipe.author.username }}
                {% endif %}
            </span>
        {% endif %}
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ recipe.created_at|date:"d/m/Y " }}às{{ recipe.created_at|date:" H:i:s" }}
        </span>
        {% if recipe.category != None %}
            <span class="recipe-author-item">
                <a href="{% url 'recipes:category' recipe.category.id %}">
                    <i class="fas fa-layer-group"></i>
                    <span>{{ recipe.category.name }}</span>
                </a>
            </span>
        {% endif %}
    </div>
    <dir class="recipe-content">
        <p>{{ recipe.description }}</p>
    </dir>
    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title">
                <i class="fas fa-stopwatch"></i> Preparo
            </h3>
            <div class="recipe-meta-text">{{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}</div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title">
                <i class="fas fa-pizza-slice"></i> Porções
            </h3>
            <div class="recipe-meta-text">{{ recipe.servings }} {{ recipe.servings_unit }}</div>
        </div>
    </div>
    {% if is_detail_page is not True %}
        <footer class="recipe-footer">
            <a class="recipe-read-more button button-dark button-full-width"
               href="{% url 'recipes:recipe' recipe.id %}">
                <i class="fas fa-eye"></i>
                <span>ver mais...</span>
            </a>
        </footer>
    {% endif %}
    {% if is_detail_page %}
        <div class="preparation-steps">
            {% if recipe.preparation_steps_is_html %}
                {{ recipe.preparation_steps|safe }}
            {% else %}
                {{ recipe.preparation_steps|linebreaks }}
            {% endif %}
        </div>
    {% endif %}
</div>

recipes/templates/recipes/partials/search.html
<div class="Serch-container">
    <div class="container">
        <form class="search-form">
            <input type="search" class="search-input" name="search">
            <button type="submit" class="search-button">
                <i class="fas fa-search"></i>
            </button>
        </form>

    </div>
</div>